# EXAMPLE FILE

# Enable basic auth with these keys
# HTTP_USER: user
# HTTP_PASS: password

# Canonical URL
DOMAIN: "http://localhost:3000"

# Sending email
MAILER_HOST: "127.0.0.1"
MAILER_PORT: "1025"
MAILER_FROM_ADDRESS: "develop@exportingisgreat.gov.uk"
MAILER_NOREPLY_ADDRESS: 'noreply@exportingisgreat.gov.uk'

# Redis
REDIS_URL: redis://localhost:6379

#use a different database for testing
test:
  REDIS_URL: redis://localhost:6379/7

COMPANIES_HOUSE_API_TOKEN: example_token
COMPANIES_HOUSE_BASE_URL:

# Google Tag Manager for analytics, comma-separated
GOOGLE_TAG_MANAGER_KEYS:

# Single Sign-on
SSO_CLIENT_ID: ''
SSO_CLIENT_SECRET: ''
SSO_ENDPOINT_BASE_URI: 'https://sso.example.org/'
SUD_PROFILE_PAGE: ''
SUD_PROFILE_PAGE_EMAIL_ALERTS: ''

# Links to CMS domain
CMS_BASE_URI: 'https://export.great.gov.uk/'

# Enquiry feedback
FEEDBACK_ENCRYPTION_SECRET: 'secret'

production:
    ENQUIRIES_CC_EMAIL:

flipper_whitelist: 'email@example.com'
legacy_domain: 'exportingisgreat.gov.uk'

api_profile_dashboard_shared_secret: 'taki'
ACTIVITY_STREAM_ACCESS_KEY_ID: '12345'
ACTIVITY_STREAM_SECRET_ACCESS_KEY: '?[!@$%^%'
ACTIVITY_STREAM_IP_WHITELIST: '0.0.0.0'

# Elasticsearch
elastic_search_url: 'http://localhost:9200'
AWS_ACCESS_KEY_ID: ''
AWS_SECRET_ACCESS_KEY: ''
AWS_REGION: ''

#clamAV virus scanning
CLAM_AV_HOST: ''
CLAM_AV_USERNAME: ''
CLAM_AV_PASSWORD:

SENTRY_RAVEN_DSN: 'http://sentry.example.org/'

post_user_communication_s3_bucket: ''

# Links to "external services" or, websites
TRADE_GREAT_GOV_UK: 'https://trade.great.gov.uk'
OFFICE_FINDER_BASE_URL: 'https://www.contactus.trade.gov.uk/office-finder/'
TRADE_PROFILE_CREATE_WITHOUT_NUMBER: 'https://find-a-buyer.export.great.gov.uk'
TRADE_PROFILE_CREATE_WITH_NUMBER: 'https://find-a-buyer.export.great.gov.uk/register/company?company_number='
# Supress Announcement - we detect its presence or absence and only need it in CI environment
SUPPRESS_ANNOUNCEMENT: "true"

GREAT_GOV_URL: 'https://great.gov.uk/export'
EXPORT_READINESS_URL: 'https://great.gov.uk/export'
SELLING_ONLINE_OVERSEAS_URL: 'https://selling-online-overseas.export.great.gov.uk'
FIND_A_BUYER_URL: 'https://find-a-buyer.export.great.gov.uk'
EVENTS_URL: 'https://events.trade.gov.uk'

REPORT_TARGETS_URL: 'https://private-url-with-csv-formatted-file'
UNSUBSCRIBE_EMAILS_URL: 'https://private-url-with-csv-formatted-file'

# production level settings for max result window size on subscription/opportunity
OPPORTUNITY_ES_MAX_RESULT_WINDOW_SIZE: '100000'
SUBSCRIPTION_ES_MAX_RESULT_WINDOW_SIZE: '50000'

# optional env vars
IMPACT_EMAIL_CHANGE_FREQUENCY: '2018-07-30'